### ISSUE TITLE
Grammar for comments within build text

### ISSUE THREAD

**Issue by NedJackman** [gregtyler/atom-sits#1]
Would it be possible to add grammar rules to capture comments in build text?
E.g. {{--This comment here--SEL:(1=1):abc}}

Image preview:
![image](https://cloud.githubusercontent.com/assets/20355124/17013853/552f6d4a-4f64-11e6-91d2-a381d985f418.png)

**Comment by gregtyler** [comment]
I didn't know you could do that, but it was easy enough to add.
